### ISSUE TITLE
Dashboard does not shows data

### ISSUE THREAD

**Issue by davidmpaz** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#17]
Hi,

thanks for this project, it had helped me to learn a lot from Influxdb/Grafana/Jmeter.

Even though i have followed your instructions i can not manage to show metrics on the dashboard panels.

* I can confirm Jmeter writes data into InfluxDB since i can see it on the bucket via InfluxDB explorer UI.
    * If i try one of your Dashboard queries on the InfluxDB Data Explorer i can get data shown from it.
* I can confirm Grafana can connect to InfluxDB since the Datasource Test connection give me a green success notification on the UI also, it also recognises how many buckets InfluxDB has.

Any idea what could be happening?

Thanks in advance for your time,
Regards,
David

**Comment by mderevyankoaqa** [comment]
Hi @davidmpaz,

Is the time range correct in grafana? 
![image](https://user-images.githubusercontent.com/58083002/118406897-b1cff180-b686-11eb-96cd-efea8c333de6.png)

the connections string in my config looks like that 
![image](https://user-images.githubusercontent.com/58083002/118407056-90233a00-b687-11eb-9cb3-9ca74c26208a.png)

BR,
Mike

**Comment by mderevyankoaqa** [comment]
Can you try to change the date - time frame?

![image](https://user-images.githubusercontent.com/58083002/120504976-3df35000-c3cd-11eb-9c0e-cf8f9c18a8b9.png)

**Comment by davidmpaz** [comment]
Hi @mderevyankoaqa,

thanks for answering. I will try in the followings days and will comeback with the results.

**Comment by aivasiuk33** [comment]
Hi @mderevyankoaqa

Sorry for disturbing you, but I need some help from you.

I set up everything correctly and seeing results in grafana as below
<img width="1443" alt="Screenshot 2021-10-20 at 13 56 17" src="https://user-images.githubusercontent.com/53394375/138080725-cf6f6051-0955-4caf-9243-36ecbe389ece.png">

But whatever I do, I do not see data on Percentile graphs.
<img width="1463" alt="Screenshot 2021-10-20 at 13 56 32" src="https://user-images.githubusercontent.com/53394375/138080797-d9d14891-746f-4c61-8e63-f7b7f7706be7.png">

Can you advise what can be a reason?

P.S. I do not see Percentile data in InfluxDB as well

Thanks in advance,
Andrii

**Comment by mderevyankoaqa** [comment]
@aivasiuk33 

Hi what is Grafana server you have used?  It seems I have preproduced this issue, I've just used v8.2.3 (fb85ed6912). For now have impression that board need to be supported for the latest version.  

BR,
Mike

**Comment by aivasiuk33** [comment]
Hi @mderevyankoaqa 

We are using v8.1.5.  Then we will update to the latest version and then will try one more time.

Thank you!
Andrii

**Comment by mderevyankoaqa** [comment]
For sure its not working in v8.2.3 I see the same like you posted. Its dummy black chart.

BR,
Mike

**Comment by aivasiuk33** [comment]
Ohh, and what is the last working version of Grafana where this chart was working? (like you have when develop this board)

**Comment by mderevyankoaqa** [comment]
In the latest version we can have 

![image](https://user-images.githubusercontent.com/58083002/140074850-655fde16-d212-4992-a2be-e0875f5a73fe.png)

instead of bars (but I like bars more). What do you think?

The bars maybe was developed on GRAFANA 7.3.1. 

Also I have seen that starting from 8.x license changed from Apache 2.0 to  AGPLv3... hm.. Will take a look at the latest 7.x.

BR,
Mike

**Comment by aivasiuk33** [comment]
Hi @mderevyankoaqa 

Will try to check later next week as well

**Comment by mderevyankoaqa** [comment]
Supported latest Grafana, see the latest here https://grafana.com/grafana/dashboards/13644
