### ISSUE TITLE
Strange looking virtual user count in average response time graph 

### ISSUE THREAD

**Issue by pooventhan** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#19]
We've been using this plugin for quite some time and I must say it has a comprehensive set of charts that are really helpful in explaining performance indicators.

Recently, we tried running the JMeter test with multiple workers (2 workers), and below is the output we observed in the average response time graph:
![image](https://user-images.githubusercontent.com/35288391/125843389-dc0e9781-5efe-442b-8313-6730f50c41b5.png)

The virtual user count line went beyond the test duration (which is 10 minutes).

We attempted to reproduce this with `org.apache.jmeter.visualizers.backend.influxdb.InfluxdbBackendListener` (official JMeter implementation) and we observed the following:
![image](https://user-images.githubusercontent.com/35288391/125843951-5995547f-ae31-446b-871a-67fa191ba64a.png)

Hence we're wondering what could cause the virtual user count to extend beyond test duration in the first graph?

Here's the query for 2nd graph just in case:

```
from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "jmeter")
  |> filter(fn: (r) => r["_field"] == "avg")
  |> filter(fn: (r) => r["statut"] == "ok")
  |> aggregateWindow(every: ${aggregation}s, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

```
from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "jmeter")
  |> filter(fn: (r) => r["_field"] == "meanAT")
  |> aggregateWindow(every: ${aggregation}s, fn: mean, createEmpty: false)
  |> keep(columns: ["_time", "_value", "_field"])
```

We would really appreciate it if you could shed some light on this. Thanks in advance!

**Comment by mderevyankoaqa** [comment]
Hi @pooventhan, on the first chart you can see the such users chart maybe due to in the plugin we have async await (asynchronously) in the implementation of the data sending to flux. Jmeter do not waits when data is placed. It means threads will die with some prolongation when data sending is finished. It seems like that. 

BR,
Mike

**Comment by pooventhan** [comment]
Hi @mderevyankoaqa , it turns out that the official plugin `org.apache.jmeter.visualizers.backend.influxdb.InfluxdbBackendListener` accumulates data collection for a short period before pushing over to Influx. Besides, the payload isn't comprehensive compared to yours i.e: properties such HTTP status code, response body have been omitted. Hence, it sends data to the server faster and gets processed fast.
