### ISSUE TITLE
LP test in influxBD could not finish

### ISSUE THREAD

**Issue by alexkorotysh** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#25]
Hi Michail
I have a question about the situation, when we start JMeter distributed test with 10 or 40 slaves on 10k uses, in Grafana we could not see that test is over. 
![jmeter1](https://user-images.githubusercontent.com/15368568/134314306-d7a75191-3c0d-470c-b8d1-cc47b376033c.png)

Maybe have you ever faced it? 
I think it can be related with JMeter master can not statistic from one or more slaves at the end of testing
I'll appreciate any help!

**Comment by alexkorotysh** [comment]
```
com.influxdb.client.write.events.WriteRetriableErrorEvent logEvent
WARNING: The retriable error occurred during the writing of data. Reason: 'Failed to connect to XXX.XXX.XXX/YY.YY.YY.YY:8086'. Retry in: 6.757s.
```

**Comment by alexkorotysh** [comment]
As I understand, the backend listener is working async and after the finished 1-hour test we have to wait 30-40 mins, maybe more to pushing data into InfluxDB. I watch on request count and compare it with the request count in the Jmeter log.

**Comment by alexkorotysh** [comment]
![jmeter2](https://user-images.githubusercontent.com/15368568/134381286-ff01babe-88ab-4c5b-a2ab-181dce0f5142.png)

**Comment by mderevyankoaqa** [comment]
Hi @alexkorotysh, the plugin works in async mode, in this way JMeter should not wait when InfluxDb publish data. If we are taking the sinc mode we can have some lags from the JMeter side - JMeter will wait extra time to make sure that data is posted to InfluxDb, then go to make a new request. 

For the testing in cluster / or huge load you have to make sure that you have enough hardware on InfluxDb side to process the injections data from JMeter side and viewing the Grafana board (sure depends from your targets). 
You can take a look at the statistics from [ConsoleStatusLogger](https://jmeter-plugins.org/wiki/ConsoleStatusLogger/ ) on the slaves. To check if you have lags  on the JMeter Side you need to check If you see big difference between Latency and Resp.Time 
![image](https://user-images.githubusercontent.com/58083002/134467681-806ea687-20ef-4f0c-af76-38352e44eb5d.png)
For the normal situation Latency and Resp.Time should be almost the same.


So from the post as you said I can say InfluxDb got stuck .. As an option I have been thinking to have  "sinc mode" as an option. What do you think? in this case you can try to do the tests and see data immediately, but anyway in both cases you need to control JMeter side (at least Latency and Resp.Time, CPU, Memory so on)..

BR,
Mike

**Comment by mderevyankoaqa** [comment]
You can try [plugin](https://drive.google.com/drive/folders/1tgbK0WE0MDu_fB6bpVkC9ArG2xrKMgrr?usp=sharing) --> this one works using[Synchronous blocking API](https://github.com/influxdata/influxdb-client-java/tree/master/client#synchronous-blocking-api)

Please let me know if this version helps.. will make the release with options to choose sync or async mode. Please do not forget to monitor JMeter and InfluxDB.

BR,
Mike

**Comment by alexkorotysh** [comment]
I come back with results from testing, during 10k test with 1.2m requests today I found that max inserting into InfluxDB around 800 IOPS and utilization disk 100%. But servers have 16000 IOPS, and the synthetic test result on the server was around 5000 IOPS.
![jmeter3](https://user-images.githubusercontent.com/15368568/134505502-1f728217-b3f1-4c67-bd60-f89a4b7d0d71.png)
![jmeter4](https://user-images.githubusercontent.com/15368568/134505787-d309b117-4aac-45c2-880e-6d33c28f5e07.png)

I tried to read this article https://docs.influxdata.com/influxdb/v2.0/write-data/best-practices/optimize-writes/ , but looks like writing on plugin.


For me, async is not a problem during tests, but inserting is very slow. InfluxDB work with docker installation, but IOPS test the same in docker container.

**Comment by alexkorotysh** [comment]
I'll try to use the 2.0th version of the plugin and will come back with results.

**Comment by alexkorotysh** [comment]
Hi Michail again
with 2.0 version of the plugin, we have the same problem, we have a delay with pushing data into 
![image](https://user-images.githubusercontent.com/15368568/134641628-f90dad79-a3f3-4257-9a44-a7f15fd289d8.png)

What do you think about it? Maybe the plugin has optimal data schema

**Comment by mderevyankoaqa** [comment]
Got you, please ping me m.v.derevyanko@gmail.com to have a meeting.
BR, 
Mike

**Comment by mderevyankoaqa** [comment]
Ping me m.v.derevyanko@gmail.com to have a meeting

**Comment by mderevyankoaqa** [comment]
Discussed the details in the private chat.

**Comment by mderevyankoaqa** [comment]
@alexkorotysh The plugin performance is going to be updated in the next release. 

BR,
Mike
