### ISSUE TITLE
clarification about Java version?

### ISSUE THREAD

**Issue by aivasiuk33** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#26]
Hi @mderevyankoaqa 

Can you clarify point about java version?
It strictly should be java version 11
Or we can upgrade java to version 17?

**Comment by mderevyankoaqa** [comment]
Hi @aivasiuk33,

Need to take a look, since some custom libs has been used. For example the plugin works with Java 15. 

BR,
Mike

**Comment by mderevyankoaqa** [comment]
The update - got information from community that the plugin works with  Java 17.  I can say that Java 11 is minimum version, since some custom libs require that.

BR,
Mike

**Comment by aivasiuk33** [comment]
Thanks!
