### ISSUE TITLE
Bug: Plugin not work properly within Test Fragment 

### ISSUE THREAD

**Issue by amelkikh** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#39]
Hi!
There is no data for `requestsRaw`, `responseError` measurements when add listener within Test Fragment.
Is this possible at all?

- Grafana 8.3.3
- InfluxDB 2.1.1
```
java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
![Screenshot from 2022-01-20 05-12-05](https://user-images.githubusercontent.com/5112566/150265930-66e3d980-e3c1-4a6e-94cd-9f51cf003878.png)
![Screenshot from 2022-01-20 05-17-25](https://user-images.githubusercontent.com/5112566/150266033-b9d93ea4-8cd9-44cb-83ae-f8ee48f54dc1.png)
![Screenshot from 2022-01-20 05-18-13](https://user-images.githubusercontent.com/5112566/150266087-698a3bfb-16a0-4fcd-8d6a-c60cb22f14e2.png)
![Screenshot from 2022-01-20 05-31-55](https://user-images.githubusercontent.com/5112566/150267314-92bb8956-c992-458c-86ac-e490fd359851.png)
![Screenshot from 2022-01-20 05-32-31](https://user-images.githubusercontent.com/5112566/150267364-864bdafb-095a-4880-b470-e33c5f92db1e.png)

Thanks for you attention

**Comment by mderevyankoaqa** [comment]
Hi @amelkikh, any logs from JMeter in case of issue you have to see the records started from the things 
2022-01-24 16:53:11,846 INFO o.m.j.i.v.InfluxDatabaseBackendListenerClient:... 

Or any other errors from JMeter.. ???

We have no any dependency on the test fragments.. My private email m.v.derevyanko@gmail.com for the direct support.

BR,
Mike

**Comment by mderevyankoaqa** [comment]
Closed - configuration as a mismatch.  No one has been faced with that issue.

BR,
Mike
