### ISSUE TITLE
Jmeter gets freezed

### ISSUE THREAD

**Issue by juanma31x** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#4]
Hello! I´ve been trying to use this plugin but when I execute the test jmeter gets freezed it seems that it isn´t running anything but execution cant be stopped, I have to kill de process in order to close jmeter. And it´s not logging in influx DB

I´m using jmeter 5.4.1, Java 11and influx db 2.0

**Comment by mderevyankoaqa** [comment]
Hi @juanma31x  any logs from the JMeter? The possible causes -  wrong configuration, lack of the permissions in the Influx DB for the selected tokens. The plugin has retries functionality - in case of the fails, there are attempts to send data it may lead to the behavior you described. 
Please check also the output in the console from the JMeter process, like on the screen, you can see the error in the end.
![image](https://user-images.githubusercontent.com/58083002/108216848-9878e100-713b-11eb-8792-981c02ac6867.png)
BR,
Mike

**Comment by mderevyankoaqa** [comment]
Closed since has no details.. it looks like configuration issue.
