### ISSUE TITLE
Question - Is this plugin available in maven repository?

### ISSUE THREAD

**Issue by abygeorgea** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#41]
I am using https://github.com/jmeter-maven-plugin/jmeter-maven-plugin for running performance test in CI/CD pipeline. This can download all required plugins as needed from maven 

Is jmeter-influxdb2-listener-plugin available in maven repository?

**Comment by mderevyankoaqa** [comment]
Hi @abygeorgea the plugin is not available in maven repository for now. Let me plan this!

BR,
Mike

**Comment by pooja4099** [comment]
I am having the same challenge as @abygeorgea. i am using maven jmeter plugin and cant find it in maven. @mderevyankoaqa Could you please help at the earliest. I am using the below for now but its not providing most of the stats. 
![image](https://user-images.githubusercontent.com/47227812/171747369-1c0d08c4-7e8e-4c37-b6a8-72fc390579db.png)

**Comment by mderevyankoaqa** [comment]
Hi @abygeorgea, the plugin is available in maven https://s01.oss.sonatype.org/content/repositories/releases/io/github/mderevyankoaqa/jmeter-plugin-influxdb2-listener/maven-metadata.xml

 @pooja4099 are you looking for the plugin from the JMeter plugin manager? My plugin is not available in https://jmeter-plugins.org/wiki/PluginsManager/ (its not the maven storage, its the JMeter storage, JFYI). You need to pass the instructions to deploy this plugin manually https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin#deployment
Have you done that?
  
BR,
Mike

**Comment by pooja4099** [comment]
Thanks for a quick response Mike, so i am also using maven jmeter plugin to download and manage plugins.
![image](https://user-images.githubusercontent.com/47227812/171902818-fb8d99f2-3298-4f9d-a207-0eb73e964126.png)
so now i can see the option in the backend listener dropdown but getting an error 
![image](https://user-images.githubusercontent.com/47227812/171903540-1c7f547c-9fdd-4e62-abe1-5e92c10de212.png)

_```
2022-06-03 17:05:53,677 ERROR o.a.j.v.b.BackendListenerGui: Error getting argument list for io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient
java.lang.reflect.InvocationTargetException: null
```_

**Comment by mderevyankoaqa** [comment]
@pooja4099 alright got you. I will release soon the plugin 2.0 it seems the issue is due to the renaming of the package, which leads to the errors. Why 2.0? - Braking changes - the old users need to update the plugin and select the JMeter proper plugin name. 

BR,
Mike

**Comment by mderevyankoaqa** [comment]
@abygeorgea, @pooja4099 I've managed to release 2.0 version the POM xml is please try!

The URL is the same https://s01.oss.sonatype.org/content/repositories/releases/io/github/mderevyankoaqa/jmeter-plugin-influxdb2-listener/maven-metadata.xml

`<metadata>
<groupId>io.github.mderevyankoaqa</groupId>
<artifactId>jmeter-plugin-influxdb2-listener</artifactId>
<versioning>
<latest>2.0</latest>
<release>2.0</release>
<versions>
<version>1.6</version>
<version>2.0</version>
</versions>
<lastUpdated>20220603205720</lastUpdated>
</versioning>
</metadata>`

BR,
Mike

**Comment by pooja4099** [comment]
Hi Mike, same behavior now also,
![image](https://user-images.githubusercontent.com/47227812/172018259-4b254702-4f32-4027-a5e5-7f48eeb2468b.png)
2022-06-04 18:18:15,567 ERROR o.a.j.v.b.BackendListenerGui: Error getting argument list for io.github.mderevyankoaqa.influxdb2.visualizer.InfluxDatabaseBackendListenerClient
java.lang.reflect.InvocationTargetException: null

**Comment by mderevyankoaqa** [comment]
Hi @pooja4099, please contact me directly by email or skype to plan the support session, I have no CI/CD to test right now. 

skype: michal_v_derevyanko, gmail: m.v.derevyanko@gmail.com

BR,
Mike

**Comment by mderevyankoaqa** [comment]
@pooja4099, 

I've investigated the issue and will try to improve that in the future. For now please see the steps.
1. I used the the maven plugin like in the article https://www.ubik-ingenierie.com/blog/shift-left-performance-tests-jmeter-maven/?cn-reloaded=1
2. in that plugin I added the all dependencies the current plugin needs, see example bellow:
          ` <jmeterExtensions>`
                    ` <artifact>io.github.mderevyankoaqa:jmeter-plugin-influxdb2-listener:2.0</artifact>`
                    `<artifact>com.influxdb:influxdb-client-java:6.1.0</artifact>`
                    `<artifact>org.apache.jmeter:jorphan:5.4.3</artifact>`
                    `<artifact>org.apache.commons:commons-lang3:3.12.0</artifact>`
                    `<artifact>com.squareup.okhttp3:okhttp:3.12.13</artifact>`
                `</jmeterExtensions> `
          
Can you please try and let me know if its works.
Many thanks.

BR,
Mike

**Comment by mderevyankoaqa** [comment]
@pooja4099, please ignore the message above, today I will release the hotfix of the jar in maven. 

BR,
Mike

**Comment by mderevyankoaqa** [comment]
@pooja4099, you will need to put  `<artifact>io.github.mderevyankoaqa:jmeter-plugins-influxdb2-listener:2.1</artifact>`

let you know when I finish and publish the new release with fixes. It was a workaround to add all dependencies for the release 2.0.  The problem was that the target jar has Classifier="All" and the maven plugin downloads the wrong jar (source jar).

BR,
Mike

**Comment by mderevyankoaqa** [comment]
@pooja4099, the maven index has updated, JMeter works fine for me, please try and share the results.

BR,
Mike

**Comment by pooja4099** [comment]
its working now as expected mike @mderevyankoaqa 
thank you so much for the fix :)

**Comment by mderevyankoaqa** [comment]
Done.
