### ISSUE TITLE
Throughput calculation clarification

### ISSUE THREAD

**Issue by sravanthnag** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#44]
Hi,

In https://grafana.com/grafana/dashboards/13644, I see that throughput is calculated irrespective of transaction is pass or fail. There is no filter applied on a status column which Jmeter by default emits - ok and ko. 

I have tried to change the query to plot throughput through successful results only but could not plot it effectively. Any pointers to include the ok filter in throughput graphs

**Comment by mderevyankoaqa** [comment]
Hi @sravanthnag ,

Good point, let's me plan this.

BR,
Mike

**Comment by mderevyankoaqa** [comment]
@sravanthnag , 

So you want to have the possibility to see OK and KO requests on the throughput chart?

On the chart from the picture we are able to see all (OK and KO).
![image](https://user-images.githubusercontent.com/58083002/171627872-dcc8d777-c33c-4998-9e3f-f56b6d30a663.png)

BR,
Mike

**Comment by sravanthnag** [comment]
Hi Mike,

Yes, the current throughput chart brings in all OK and KO transactions. But when I checked the database for a status column to filter out based on only OK, I could not get that. So, I thought I will ask the exact query which can filter out the only OK set of transactions.

**Comment by mderevyankoaqa** [comment]
@sravanthnag  we have the possibility to filter OK and KO using 

The code above will return you KO

`|> filter(fn: (r) => r["_field"] == "errorCount")`
`|> filter(fn: (r) => r["_value"] == 1)`

I will improve in the next release.  

BR,
Mike

**Comment by sravanthnag** [comment]
Hi Mike,

I would wait for the changes to reflect. Thank you.

**Comment by sravanthnag** [comment]
Hi Mike,

Thanks for the update. This works on expected lines for me.

There are some other minor clarifications/queries for which probably I will raise a new one.
