### ISSUE TITLE
io.github.mderevyankoaqa.influxdb2.visualizer.JMeterInfluxDBBackendListenerClient not displayed in backend listener 

### ISSUE THREAD

**Issue by matifniaz** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#62]
I am using Jmeter version 5.5 and i download and place updated jar plugin (jmeter-plugins-influxdb2-listener-2.4.jar) that is required for this but after restarting Jmeter its not show in drop down other all 3 displayed in drop down.

Kindly help me to resolving this issue.

io.github.mderevyankoaqa.influxdb2.visualizer.JMeterInfluxDBBackendListenerClient

**Comment by mderevyankoaqa** [comment]
Hi @matifniaz, see answer here https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/issues/35

BR,
Mike

**Comment by matifniaz** [comment]
Thanks @mderevyankoaqa  - now its working fine for me after update my java version from 10 to 11.

**Comment by alexsom64** [comment]
Not see it in Backend listener with java 20
