### ISSUE TITLE
Times series panel connecting values between test runs even when configured to never connect null values

### ISSUE THREAD

**Issue by cassioKenji** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#63]
Hi. 
Is there a way to ged rid of connected test runs in Time Series Panel?
Thank you.

![sdd](https://user-images.githubusercontent.com/1015830/186005981-f9edd9c0-447c-42ab-98c0-1b94b853a6d3.jpeg)

**Comment by mderevyankoaqa** [comment]
Hi it seems you faced with grafana specific things. Not sure that we can play with that.
BR,
Mike
