### ISSUE TITLE
Please provide runid dropdown option too on grafana dashboard

### ISSUE THREAD

**Issue by amitngm** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#64]
Hi,

We have a requirement to see results on Grafana based on runid provided in influxdb. We need runid dropdown also on dashbaord.We are using this plugin to see live data.

Regards,
Amit

**Comment by mderevyankoaqa** [comment]
Hi, sorry was very busy. Will try to take a look.
BR, 
Mike

**Comment by amitngm** [comment]
Hi Mike, thanks for replying me from your busy schedule. 
Is there any luck ..

Regards,
Amit

**Comment by mderevyankoaqa** [comment]
@amitngm Haven't time sorry. I Hope will take a look this week at the capability that we have. By the way what Grafana version are you using? I'm going to update the board as well to use the latest.

BR,
Mike

**Comment by amitngm** [comment]
It's 9.1.1

Regards,
Amit

**Comment by amitngm** [comment]
Also, we don't find any metric for "All" sample

**Comment by mderevyankoaqa** [comment]
Hello, @amitngm I started adding the runid to the board. So we will have the capability to select one run. 

So for example you have two runs with ids 1 and 2  executed in 10 minutes. You will be able to select only run with id 1 or 2 to see the data. To see runs 1 and 2 at the same time will not be possible on the same chart. Any comment? 

"All" sample - what do you mean? describe the feature, please. 

BR,
Mike

**Comment by mderevyankoaqa** [comment]
Hi @amitngm implemented in https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/releases/tag/v2.5 

BR,
Mike

**Comment by amitngm** [comment]
Thank You Mike.

Also, All is the collection of request count defined in the suite or executed samples, avg hits, avg responses etc. are the total count or average of execution results.
